
package com.pluralsight.service.orders;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2016-09-19T19:55:55.958+02:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "errorHandler", targetNamespace = "http://www.pluralsight.com/schema/Order")
public class ProcessOrderPlacementError extends Exception {
    
    private com.pluralsight.schema.order.ErrorHandlerType errorHandler;

    public ProcessOrderPlacementError() {
        super();
    }
    
    public ProcessOrderPlacementError(String message) {
        super(message);
    }
    
    public ProcessOrderPlacementError(String message, Throwable cause) {
        super(message, cause);
    }

    public ProcessOrderPlacementError(String message, com.pluralsight.schema.order.ErrorHandlerType errorHandler) {
        super(message);
        this.errorHandler = errorHandler;
    }

    public ProcessOrderPlacementError(String message, com.pluralsight.schema.order.ErrorHandlerType errorHandler, Throwable cause) {
        super(message, cause);
        this.errorHandler = errorHandler;
    }

    public com.pluralsight.schema.order.ErrorHandlerType getFaultInfo() {
        return this.errorHandler;
    }
}
